import React, { useState } from 'react';
import {
  FileText,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Edit3,
  Save,
  Clock,
  ShieldCheck,
  Building,
  User,
  Activity,
  Layers,
  HelpCircle
} from 'lucide-react';
import { StructuredSARReport } from '../types';

interface ReportEditorProps {
  report: StructuredSARReport;
  reportStatus: string;
  onSaveReport: (updatedReport: StructuredSARReport, notes?: string) => Promise<void>;
  onApprove: (notes: string) => Promise<void>;
  onReject: (notes: string) => Promise<void>;
  isProcessing?: boolean;
}

export const ReportEditor: React.FC<ReportEditorProps> = ({
  report,
  reportStatus,
  onSaveReport,
  onApprove,
  onReject,
  isProcessing = false
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editedReport, setEditedReport] = useState<StructuredSARReport>(report);
  const [approvalModalOpen, setApprovalModalOpen] = useState(false);
  const [rejectModalOpen, setRejectModalOpen] = useState(false);
  const [decisionNotes, setDecisionNotes] = useState('');
  const [saveSuccessMsg, setSaveSuccessMsg] = useState('');

  const isApproved = reportStatus === 'APPROVED';
  const isRejected = reportStatus === 'REJECTED';

  const handleSave = async () => {
    try {
      await onSaveReport(editedReport, 'Human investigator edited report draft.');
      setIsEditing(false);
      setSaveSuccessMsg('Report edits saved successfully.');
      setTimeout(() => setSaveSuccessMsg(''), 4000);
    } catch (err: any) {
      alert('Failed to save edits: ' + (err.message || 'Unknown error'));
    }
  };

  const handleApproveConfirm = async () => {
    await onApprove(decisionNotes);
    setApprovalModalOpen(false);
    setDecisionNotes('');
  };

  const handleRejectConfirm = async () => {
    await onReject(decisionNotes);
    setRejectModalOpen(false);
    setDecisionNotes('');
  };

  return (
    <div className="space-y-6">
      {/* Top Banner: Mandatory Academic Draft Watermark */}
      <div className="p-4 rounded-xl border border-amber-500/40 bg-amber-950/30 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-lg bg-amber-500/20 text-amber-400">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className="text-sm font-bold tracking-wide uppercase text-amber-300">
                {report.case_information.watermark}
              </span>
              <span className="text-[10px] px-2 py-0.5 rounded-full font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                {reportStatus}
              </span>
            </div>
            <p className="text-xs text-slate-400">
              Generated by Fintel Multi-Agent Architecture for Academic PBL Simulation. Requires explicit human review and sign-off.
            </p>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center space-x-2">
          {!isEditing ? (
            <button
              onClick={() => setIsEditing(true)}
              disabled={isApproved || isProcessing}
              className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center space-x-1.5 transition-colors disabled:opacity-50"
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>Edit Draft</span>
            </button>
          ) : (
            <div className="flex items-center space-x-2">
              <button
                onClick={() => {
                  setEditedReport(report);
                  setIsEditing(false);
                }}
                className="px-3 py-1.5 rounded-lg text-xs font-medium text-slate-400 hover:text-slate-200 bg-slate-800/60"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                disabled={isProcessing}
                className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-cyan-500 hover:bg-cyan-400 text-slate-950 flex items-center space-x-1.5 shadow-md shadow-cyan-500/20"
              >
                <Save className="w-3.5 h-3.5" />
                <span>Save Changes</span>
              </button>
            </div>
          )}

          {!isApproved && (
            <>
              <button
                onClick={() => setRejectModalOpen(true)}
                disabled={isProcessing}
                className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-red-950/60 hover:bg-red-900/80 text-red-300 border border-red-800/60 flex items-center space-x-1.5 transition-colors"
              >
                <XCircle className="w-3.5 h-3.5" />
                <span>Send Back / Reject</span>
              </button>
              <button
                onClick={() => setApprovalModalOpen(true)}
                disabled={isProcessing}
                className="px-4 py-1.5 rounded-lg text-xs font-semibold bg-emerald-500 hover:bg-emerald-400 text-slate-950 flex items-center space-x-1.5 shadow-lg shadow-emerald-500/20 font-bold transition-colors"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>Approve SAR</span>
              </button>
            </>
          )}
        </div>
      </div>

      {saveSuccessMsg && (
        <div className="p-3 rounded-lg bg-emerald-950/50 border border-emerald-500/40 text-emerald-300 text-xs flex items-center space-x-2">
          <CheckCircle2 className="w-4 h-4" />
          <span>{saveSuccessMsg}</span>
        </div>
      )}

      {/* 9 Standard SAR Sections */}
      <div className="space-y-5 text-slate-200">
        {/* Section 1: Case Information */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>1. Case Information</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
            <div>
              <span className="text-slate-400 block">Case Reference</span>
              <span className="font-mono font-bold text-slate-100">{report.case_information.case_id}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Filing Classification</span>
              <span className="font-semibold text-slate-200">{report.case_information.filing_type}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Date Drafted</span>
              <span className="font-mono text-slate-300">{report.case_information.date_drafted}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Sign-off Status</span>
              <span className="font-bold text-amber-400">{report.case_information.human_status}</span>
            </div>
          </div>
        </section>

        {/* Section 2: Subject Information */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
            <User className="w-4 h-4" />
            <span>2. Subject Entity / Customer Information</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 text-xs">
            <div>
              <span className="text-slate-400 block">Subject Account</span>
              <span className="font-mono font-bold text-cyan-300">{report.subject_information.account_id}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Account Classification</span>
              <span className="font-semibold">{report.subject_information.account_type}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Customer ID</span>
              <span className="font-mono">{report.subject_information.customer_id}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Entity Name</span>
              <span className="font-semibold">{report.subject_information.customer_name}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Country / Corridors</span>
              <span className="font-mono">{report.subject_information.country}</span>
            </div>
            <div>
              <span className="text-slate-400 block">Baseline KYC Risk</span>
              <span className="font-bold text-red-400">{report.subject_information.customer_risk_rating}</span>
            </div>
          </div>
        </section>

        {/* Section 3: Suspicious Activity Summary */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
            <AlertTriangle className="w-4 h-4" />
            <span>3. Suspicious Activity Summary Narrative</span>
          </div>

          {isEditing ? (
            <textarea
              rows={4}
              value={editedReport.suspicious_activity_summary.narrative_summary}
              onChange={(e) =>
                setEditedReport({
                  ...editedReport,
                  suspicious_activity_summary: {
                    ...editedReport.suspicious_activity_summary,
                    narrative_summary: e.target.value
                  }
                })
              }
              className="w-full p-3 rounded-xl bg-slate-900 border border-cyan-500/50 text-xs font-sans text-slate-100 focus:outline-none focus:ring-1 focus:ring-cyan-400"
            />
          ) : (
            <p className="text-xs leading-relaxed text-slate-300 bg-slate-900/60 p-3.5 rounded-xl border border-slate-800/80">
              {report.suspicious_activity_summary.narrative_summary}
            </p>
          )}

          <div className="flex flex-wrap items-center gap-2 pt-1 text-xs">
            <span className="text-slate-400 text-[11px]">Typologies Flagged:</span>
            {report.suspicious_activity_summary.typologies_detected.map((t, idx) => (
              <span key={idx} className="px-2 py-0.5 rounded-md bg-red-950/60 border border-red-700/50 text-red-300 text-[10px] font-mono">
                {t}
              </span>
            ))}
            <span className="ml-auto text-[11px] text-slate-400">
              Total Volume: <strong className="text-emerald-400 font-mono">${report.suspicious_activity_summary.total_suspicious_volume.toLocaleString()}</strong>
            </span>
          </div>
        </section>

        {/* Section 4 & 5: Transaction & Graph Analysis */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
              <Activity className="w-4 h-4" />
              <span>4. Transaction Flow Analysis</span>
            </div>
            <div className="space-y-2 text-xs text-slate-300">
              <div className="flex justify-between">
                <span className="text-slate-400">Transactions Analyzed:</span>
                <span className="font-mono font-bold">{report.transaction_analysis.total_transactions_analyzed}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Rapid Movement / Pass-through:</span>
                <span className={report.transaction_analysis.rapid_movement_flagged ? 'text-red-400 font-bold' : 'text-slate-400'}>
                  {report.transaction_analysis.rapid_movement_flagged ? 'CONFIRMED' : 'Not Flagged'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">High-Value Volume Outliers:</span>
                <span className="font-mono font-bold text-amber-400">{report.transaction_analysis.high_value_transactions_count}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Structuring / Smurfing Evidence:</span>
                <span className="font-mono font-bold text-amber-400">{report.transaction_analysis.structuring_evidence_count}</span>
              </div>
            </div>
          </section>

          <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
              <Layers className="w-4 h-4" />
              <span>5. Graph Topology & Network Role</span>
            </div>
            <div className="space-y-2 text-xs text-slate-300">
              <div className="flex justify-between">
                <span className="text-slate-400">Network Typology Role:</span>
                <span className="font-semibold text-cyan-300">{report.graph_analysis.network_role}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Direct Counterparties:</span>
                <span className="font-mono font-bold">{report.graph_analysis.immediate_counterparties_count}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Fan-In / Fan-Out Ratios:</span>
                <span className="font-mono text-slate-200">
                  {report.graph_analysis.fan_in_ratio} / {report.graph_analysis.fan_out_ratio}
                </span>
              </div>
              <p className="text-[11px] text-slate-400 pt-1 leading-relaxed">
                {report.graph_analysis.subgraph_summary}
              </p>
            </div>
          </section>
        </div>

        {/* Section 6: Investigation Findings */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
            <ShieldCheck className="w-4 h-4" />
            <span>6. AI Investigation Findings & Evidence Grounding</span>
          </div>
          <div className="space-y-2">
            {report.investigation_findings.core_reasoning_points.map((point, idx) => (
              <div key={idx} className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-xs text-slate-300 flex items-start space-x-2">
                <span className="text-cyan-400 font-mono font-bold shrink-0">{idx + 1}.</span>
                <span className="leading-relaxed">{point}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Section 7: Risk Indicators */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
              <Activity className="w-4 h-4" />
              <span>7. Explainable Risk Score Breakdown</span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-xs text-slate-400">Composite Score:</span>
              <span className="text-sm font-bold font-mono text-red-400">
                {report.risk_indicators.composite_risk_score} / 100
              </span>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {report.risk_indicators.contributing_indicators.map((ind, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 space-y-1 text-xs">
                <div className="flex justify-between items-center">
                  <span className="font-semibold text-slate-200 font-mono">{ind.indicator}</span>
                  <span className="px-1.5 py-0.5 rounded bg-red-950 text-red-400 font-mono font-bold text-[10px]">
                    +{ind.score} pts
                  </span>
                </div>
                <p className="text-[11px] text-slate-400 leading-snug">{ind.explanation}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 8: Supporting Evidence Table */}
        <section className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>8. Supporting Evidence Ledger</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-slate-400 font-mono text-[11px]">
                  <th className="py-2 px-3">Evidence ID</th>
                  <th className="py-2 px-3">Classification</th>
                  <th className="py-2 px-3">Source Ref</th>
                  <th className="py-2 px-3">Factual Observation</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-850">
                {report.supporting_evidence.evidence_table.map((ev, idx) => (
                  <tr key={idx} className="hover:bg-slate-900/40 font-mono text-[11px]">
                    <td className="py-2 px-3 font-bold text-cyan-400">{ev.evidence_id}</td>
                    <td className="py-2 px-3 text-slate-300 font-sans">{ev.type}</td>
                    <td className="py-2 px-3 text-slate-400">{ev.source}</td>
                    <td className="py-2 px-3 font-sans text-slate-300 leading-relaxed">{ev.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Section 9: Investigator Review & Human Sign-off */}
        <section className="glass-panel-elevated p-5 rounded-2xl border border-slate-700/80 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-bold text-emerald-400 uppercase tracking-wider">
            <CheckCircle2 className="w-4 h-4" />
            <span>9. Investigator Final Determination & Human Review</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
            <div>
              <span className="text-slate-400 block">Approval Decision</span>
              <span className={`font-bold uppercase tracking-wider text-sm ${
                isApproved ? 'text-emerald-400' : isRejected ? 'text-red-400' : 'text-amber-400'
              }`}>
                {report.investigator_review_section.approval_status}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block">Reviewing Investigator</span>
              <span className="font-semibold text-slate-200">
                {report.investigator_review_section.reviewed_by || 'Awaiting Review'}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block">Determination Timestamp</span>
              <span className="font-mono text-slate-300">
                {report.investigator_review_section.reviewed_at || 'Pending'}
              </span>
            </div>
          </div>

          {report.investigator_review_section.decision_reasoning && (
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs">
              <span className="text-slate-400 block mb-1">Investigator Remarks:</span>
              <p className="text-slate-200 leading-relaxed">
                {report.investigator_review_section.decision_reasoning}
              </p>
            </div>
          )}
        </section>
      </div>

      {/* Confirmation Modal: Approval */}
      {approvalModalOpen && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-in fade-in duration-150">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6 max-w-md w-full space-y-4 shadow-2xl">
            <div className="flex items-center space-x-3 text-emerald-400">
              <CheckCircle2 className="w-6 h-6" />
              <h3 className="text-base font-bold text-slate-100">Human Approval Sign-Off</h3>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              By confirming, you record an official human sign-off on this SAR draft. The case status will transition to <strong className="text-emerald-400">APPROVED</strong> and an immutable event will be logged in the compliance audit trail.
            </p>
            <div>
              <label className="text-xs text-slate-400 block mb-1">Investigator Justification / Notes:</label>
              <textarea
                rows={3}
                value={decisionNotes}
                onChange={(e) => setDecisionNotes(e.target.value)}
                placeholder="e.g. Case examined against KYC files and cross-border bank statements. Validated typology findings."
                className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-700 text-xs text-slate-100 focus:outline-none focus:ring-1 focus:ring-emerald-400"
              />
            </div>
            <div className="flex justify-end space-x-2 pt-2">
              <button
                onClick={() => setApprovalModalOpen(false)}
                className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 text-slate-300 hover:bg-slate-700"
              >
                Cancel
              </button>
              <button
                onClick={handleApproveConfirm}
                disabled={isProcessing}
                className="px-4 py-2 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-lg shadow-emerald-500/20"
              >
                Confirm Approval
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Modal: Rejection */}
      {rejectModalOpen && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-in fade-in duration-150">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6 max-w-md w-full space-y-4 shadow-2xl">
            <div className="flex items-center space-x-3 text-red-400">
              <XCircle className="w-6 h-6" />
              <h3 className="text-base font-bold text-slate-100">Reject / Return SAR Draft</h3>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              Send this case back or mark it as rejected. Please record the regulatory reasoning or missing information required.
            </p>
            <div>
              <label className="text-xs text-slate-400 block mb-1">Reason for Rejection / Return:</label>
              <textarea
                rows={3}
                value={decisionNotes}
                onChange={(e) => setDecisionNotes(e.target.value)}
                placeholder="e.g. Activity appears consistent with legitimate seasonal agricultural trade; insufficient evidence for illicit layering."
                className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-700 text-xs text-slate-100 focus:outline-none focus:ring-1 focus:ring-red-400"
              />
            </div>
            <div className="flex justify-end space-x-2 pt-2">
              <button
                onClick={() => setRejectModalOpen(false)}
                className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 text-slate-300 hover:bg-slate-700"
              >
                Cancel
              </button>
              <button
                onClick={handleRejectConfirm}
                disabled={isProcessing}
                className="px-4 py-2 rounded-xl text-xs font-bold bg-red-600 hover:bg-red-500 text-white shadow-lg shadow-red-500/20"
              >
                Confirm Rejection
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
