/**
 * Single Source of Truth for all user-facing UI labels, headings, buttons, tooltips, and statuses.
 * 
 * Rules:
 * 1. Plain language that non-technical persons can easily understand.
 * 2. Keep regulatory terms (AML/CFT, SAR, FIU-IND, PEP, KYC) with clear plain-language subtitles or tooltips.
 * 3. Never expose technical jargon like 'schema', 'payload', 'endpoint', 'ingestion pipeline', 'k-hop subgraph' in user-facing text.
 * 4. Internal variables, API calls, and function names remain unchanged.
 */

export const LABELS = {
  // App Branding & Navigation
  app: {
    name: 'FINTEL',
    title: 'Financial Crime Investigation Tool',
    subtitle: 'Assisting investigators with transaction analysis, pattern detection, and report drafting',
    amlCftBadge: 'AML / CFT',
    amlCftTooltip: 'Anti-Money Laundering & Counter-Terror Financing',
    surveillanceLive: 'Activity Monitoring Active',
    demoModeBadge: 'Demo Mode',
    demoModeTooltip: 'Using sample data / no live AI calls',
    leadInvestigatorRole: 'Lead Investigator',
    systemAdminRole: 'System Administrator',
  },

  // Main Sidebar & Breadcrumbs Navigation
  nav: {
    coreWorkflow: 'Main Steps',
    intelligenceReports: 'Analysis & Reports',
    system: 'System',
    dashboard: 'Dashboard',
    investigationPipeline: 'Investigation Pipeline',
    casesLedger: 'Cases',
    casesLedgerTooltip: 'Record of all flagged accounts and cases',
    detectionEngine: 'Scanning for Suspicious Activity',
    detectionEngineShort: 'Activity Scanner',
    transactionGraph: 'Connections Map',
    transactionGraphShort: 'Connections',
    autonomousAgents: 'AI Assistants',
    sarReports: 'Draft Reports',
    sarReportsSubtitle: 'Suspicious Activity Reports (for FIU-IND)',
    auditTrail: 'Activity History',
    auditTrailTooltip: 'Audit trail: complete historical record of all actions taken',
    dataManagement: 'Uploads & Records',
    platformSettings: 'Settings',
    dataDictionary: 'Terms & Data Guide',
    newInvestigation: 'New Investigation',
    overview: 'Overview & Triage',
  },

  // 10-Step Pipeline Steps & Stepper
  pipeline: {
    badge: 'INVESTIGATION WORKFLOW',
    badgeSubtitle: '10-step review from raw statement to signed report',
    stagePrefix: 'Stage',
    ofTotal: 'of 10',
    progressCompleted: 'Completed',

    // Stage 1: Upload
    stage1: {
      id: 1,
      name: 'Upload Statement',
      shortLabel: 'Upload',
      title: 'Upload Bank Statement or Transaction File',
      subtitle: 'Select or drop a bank statement (CSV or Excel) to start the investigation.',
      fileValidated: 'File Verified',
      dropzoneTitle: 'Drag and drop your transaction file here',
      dropzoneSubtitle: 'Supports banking statements (.CSV, .XLSX, .XLS up to 50,000 rows)',
      browseFiles: 'Browse Local Files',
      changeFile: 'Choose a Different File',
      verifiedReady: 'Verified & Ready to Read',
      sampleSectionTitle: 'Need Sample Data?',
      sampleSectionSubtitle: 'Load realistic bank data with common suspicious activity patterns (like structuring and circular transfers).',
      sampleButton: 'Load Sample Bank Statement',
      sampleLoading: 'Loading Sample Data...',
      proceedButton: 'Proceed to Read Data',
    },

    // Stage 2: Reading & Organizing Your Data (formerly Data Ingestion)
    stage2: {
      id: 2,
      name: 'Reading & Organizing Your Data',
      shortLabel: 'Read Data',
      title: 'Reading & Organizing Your Data',
      subtitle: 'The system cleans your file and organizes every transaction into clear, consistent columns.',
      rowsProcessed: 'Rows Processed',
      validatedStructure: 'Format Checked',
      differentAccounts: 'Different Accounts Found',
      accountsSubtext: 'Main Account + Other Parties',
      dataQuality: 'Data Quality Check',
      qualitySubtext: 'All required transaction details present',
      previewTitle: 'Organized Transactions Preview',
      table: {
        txnId: 'Transaction ID',
        mainAccount: 'Main Account',
        otherParty: 'Other Party',
        dateTime: 'Date & Time',
        amount: 'Amount',
        description: 'Description',
      },
      loading: 'Reading and organizing transaction records...',
      backButton: 'Back to Upload',
      proceedButton: 'Scan for Suspicious Activity',
    },

    // Stage 3: Scanning for Suspicious Activity (formerly Detection Engine)
    stage3: {
      id: 3,
      name: 'Scanning for Suspicious Activity',
      shortLabel: 'Scan Activity',
      title: 'Scanning for Suspicious Activity',
      subtitle: 'Checking transactions against known financial crime patterns, transfer sizes, and abnormal flow speeds.',
      statusTitle: 'Scanning Status',
      evaluatingSubtitle: 'Checking transfer patterns...',
      completedSubtitle: 'Scan complete across all suspicious activity patterns.',
      evaluatedTxns: 'Total Transactions Checked',
      flaggedAnomalies: 'Flagged Transactions',
      activeRules: 'Patterns Checked',
      accuracyRating: 'Detection Accuracy',
      processingBadge: 'Processing...',
      completedBadge: 'Completed',
      thresholdLabel: 'Rule Limit:',
      backButton: 'Back to Read Data',
      proceedButton: 'View Flagged Transactions',
      rules: {
        structuring: {
          name: 'Structuring (Amounts Just Below $10K Limit)',
          description: 'Splitting larger sums into smaller deposits to avoid regulatory reporting.',
          threshold: '$9,000 - $9,999',
        },
        rapidPass: {
          name: 'Fast Pass-Through (Money In & Quickly Out)',
          description: 'Money arriving and leaving within a very short timeframe.',
          threshold: 'Under 60 Minutes',
        },
        fanOut: {
          name: 'Money Mule Dispersion (One-to-Many)',
          description: 'One account sending funds to multiple recipients in quick succession.',
          threshold: '4 or more recipients',
        },
        circularLoop: {
          name: 'Circular Money Flow (Round-Tripping)',
          description: 'Funds sent in loops through intermediaries to hide the true source.',
          threshold: 'Circular Path Detected',
        },
        highValue: {
          name: 'Unusually Large Transfer',
          description: 'Single large transfers exceeding typical account activity.',
          threshold: '$50,000 or more',
        },
      },
    },

    // Stage 4: Flagged Transactions
    stage4: {
      id: 4,
      name: 'Flagged Transactions',
      shortLabel: 'Flagged Txns',
      title: 'Flagged Transactions',
      subtitle: 'These transactions were flagged during the scan as abnormal or high risk. Each entry shows the reason it was flagged.',
      tableTitle: 'List of Flagged Transactions',
      flaggedCountBadge: 'Flagged',
      table: {
        txnId: 'Transaction ID',
        mainAccount: 'Main Account',
        otherParty: 'Other Party',
        amount: 'Amount',
        dateTime: 'Date & Time',
        reason: 'Reason Flagged',
        riskLevel: 'Risk Level',
      },
      backButton: 'Back to Activity Scan',
      proceedButton: 'Calculate Account Risk Level',
    },

    // Stage 5: Risk Level (formerly Risk Scoring / Composite Risk Score)
    stage5: {
      id: 5,
      name: 'Risk Level',
      shortLabel: 'Risk Level',
      title: 'Account Overall Risk Level & Why',
      subtitle: 'Combines how often, how fast, and how much money moved through this account into an easy-to-understand 0–100 risk rating.',
      mainAccountLabel: 'Main Account Flagged',
      overallRatingLabel: 'Overall Risk Level',
      scoreOutOf100: '/ 100',
      whyTitle: 'Why This Account Was Given This Risk Level',
      pointsBreakdownLabel: 'Points Breakdown',
      computingText: 'Calculating risk level...',
      backButton: 'Back to Flagged Transactions',
      proceedButton: 'View Connections Map',
    },

    // Stage 6: Connections Map (formerly Transaction Graph / k-hop subgraph)
    stage6: {
      id: 6,
      name: 'Connections Map',
      shortLabel: 'Connections',
      title: 'Account Connections Map',
      subtitle: 'Shows how money moves between this account and connected accounts. Click any account circle or connection line to see details.',
      loadingText: 'Building connections map...',
      backButton: 'Back to Risk Level',
      proceedButton: 'Run AI Review & Explanation',
    },

    // Stage 7: AI Review & Explanation (formerly AI Investigation)
    stage7: {
      id: 7,
      name: 'AI Review & Explanation',
      shortLabel: 'AI Review',
      title: 'AI Review & Case Explanation',
      subtitle: 'The AI reviews the account transactions and explains why they look suspicious. Every point made is backed by proof from real transactions.',
      disclaimerTitle: 'AI SUMMARY — REQUIRES INVESTIGATOR REVIEW & SIGN-OFF',
      disclaimerSubtitle: 'Created from verified database records. Must be approved by an investigator before filing.',
      groundedBadge: 'Every Claim Backed by Data',
      loadingText: 'AI assistant is reviewing transactions and compiling explanation...',
      executiveSummaryTitle: 'Executive Summary',
      keyFindingsTitle: 'Key Findings & Linked Proof',
      reasoningTitle: 'How the AI Reached This Conclusion',
      uncertaintiesTitle: 'Unconfirmed Details & Questions to Check',
      backButton: 'Back to Connections Map',
      proceedButton: 'View Supporting Transactions',
    },

    // Stage 8: Supporting Transactions (formerly Cited Evidence Matrix)
    stage8: {
      id: 8,
      name: 'Supporting Transactions',
      shortLabel: 'Supporting Proof',
      title: 'Supporting Transactions & Proof',
      subtitle: 'Every statement made by the AI links directly to an actual transaction record. Click any row to see the exact transaction.',
      claimMapTitle: 'Linked Proof by Claim',
      coverageBadge: 'All Claims Backed by Proof',
      sourceTx: 'Transaction',
      whatAiSaid: 'What the AI Stated:',
      transactedAmount: 'Amount',
      mainAccount: 'Main Account',
      otherParty: 'Other Party',
      directionMethod: 'Direction & Method',
      backButton: 'Back to AI Review',
      proceedButton: 'Create Draft Report',
    },

    // Stage 9: Draft Report (formerly FIU-IND SAR Draft)
    stage9: {
      id: 9,
      name: 'Draft Report',
      shortLabel: 'Draft Report',
      title: 'Draft Report (Official Format)',
      subtitle: 'Prepared in the standard format required for official reporting to FIU-IND. This initial draft is ready for your review.',
      watermarkBanner: 'DRAFT REPORT — REQUIRES INVESTIGATOR REVIEW',
      watermarkSub: 'Formatted for official regulatory review. You can edit this in the next step.',
      fiuHeading: 'FINANCIAL INTELLIGENCE UNIT - INDIA',
      fiuSubheading: 'SUSPICIOUS ACTIVITY REPORT (SAR)',
      filingDate: 'Filing Date',
      refCode: 'Reference',
      partA: 'Part A: Reporting Bank & Officer Details',
      partB: 'Part B: Account & Customer Details',
      partC: 'Part C: Summary of Flagged Activity',
      partD: 'Part D: Case Explanation & Findings',
      partE: 'Part E: Recommended Action',
      institutionName: 'Bank / Institution Name',
      entityCode: 'Institution Code',
      designatedOfficer: 'Investigator / Reporting Officer',
      subjectAccount: 'Main Account Number',
      customerEntity: 'Customer / Business Name',
      taxId: 'Tax / Identity Number (PAN)',
      kycRating: 'KYC Risk Rating',
      operatingCorridor: 'Jurisdiction / Region',
      suspiciousVolume: 'Flagged Total Amount',
      txnCount: 'Flagged Transactions',
      temporalWindow: 'Time Window',
      activityType: 'Activity Type',
      backButton: 'Back to Supporting Transactions',
      proceedButton: 'Proceed to Investigator Review & Sign-off',
    },

    // Stage 10: Investigator Review & Sign-off (formerly Human Review)
    stage10: {
      id: 10,
      name: 'Investigator Review & Sign-off',
      shortLabel: 'Sign-off',
      title: 'Investigator Review & Final Sign-off',
      subtitle: 'The final decision is yours. Review the AI draft, make any needed edits or notes, and record your official sign-off.',
      aiDraftHeading: 'AI Initial Draft (Reference Only)',
      aiDraftBadge: 'NEEDS REVIEW',
      investigatorHeading: 'Your Edited Report (Official)',
      investigatorBadge: 'FINAL VERSION',
      editableNarrativeLabel: 'Case Explanation (You can edit this)',
      investigatorNotesLabel: 'Investigator Notes & Reason for Decision',
      investigatorNotesPlaceholder: 'Record your notes and reason for your decision here...',
      recommendedActionLabel: 'Recommended Next Steps',
      checklistTitle: 'Reviewer Checklist',
      checklistItems: {
        kyc: 'I checked the account and customer identity details',
        evidence: 'I reviewed the supporting transactions',
        typology: 'I confirmed the type of suspicious activity',
        approved: 'I approve this report for filing',
      },
      statusApproved: 'APPROVED & SIGNED OFF',
      statusRejected: 'RETURNED / REJECTED',
      viewInReports: 'View in Reports',
      viewInAudit: 'View Activity History',
      backButton: 'Back to Draft Report',
      rejectButton: 'Return / Reject',
      approveButton: 'Approve & Sign Off',
      modalConfirmTitle: 'Confirm Official Sign-off',
      modalConfirmDesc: 'You are about to sign off on this report. A permanent entry with your name and time will be recorded in the activity history.',
      modalCancel: 'Cancel',
      modalConfirmBtn: 'Yes, Sign Off',
      modalRejectTitle: 'Return or Reject Case',
      modalRejectDesc: 'Provide a reason for returning or rejecting this case.',
      modalRejectPlaceholder: 'Enter reason for returning (e.g. need additional customer documents)...',
      modalRejectConfirmBtn: 'Confirm Return / Reject',
    },
  },

  // Common Table, Form & Button Controls
  common: {
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    proceed: 'Proceed',
    exportPdf: 'Export PDF',
    exportDocx: 'Export Word (DOCX)',
    close: 'Close',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    account: 'Account',
    customer: 'Customer',
    riskLevel: 'Risk Level',
    overallRisk: 'Overall Risk Level',
    loading: 'Loading...',
    noData: 'No records found',
    showingResults: 'Showing results',
    viewDetails: 'View Details',
    openCase: 'Open Case',
  },

  // Data Files & Ingestion Management
  dataManagement: {
    eyebrow: 'Reading & Organizing Your Data',
    title: 'Data Files & Ingestion',
    subtitle: 'Import your customer, account, and transaction records, check for missing details, and scan for suspicious financial activity.',
    loadDemoButton: 'Load Demo Data',
    loadDemoLoading: 'Loading Demo Data...',
    loadDemoSuccess: 'Demo dataset loaded successfully',
    runDetectionButton: 'Scan for Suspicious Activity',
    runDetectionLoading: 'Scanning...',
    refreshButton: 'Refresh',
    metrics: {
      totalCustomers: 'Total Customers',
      activeAccounts: 'Active Accounts',
      totalTxns: 'Total Transactions',
      scannerStatus: 'Data Scanner Status',
      scannerActive: 'ACTIVE (Ready)',
      verifiedProfiles: 'Identity-Verified Profiles',
      connectedAccounts: 'Connected Bank Accounts',
      recordedTransfers: 'Recorded Transfers',
      realtimeCheck: 'Real-Time Quality Check',
    },
    uploadCardsTitle: 'Import Data Files',
    customerCard: {
      title: 'Customer Directory',
      description: 'Customer personal and business profiles with location, occupation, and baseline risk rating.',
    },
    accountCard: {
      title: 'Account Registry',
      description: 'Checking, savings, and corporate accounts linked to customer profiles.',
    },
    txnCard: {
      title: 'Transaction Records',
      description: 'Chronological wire, bank transfer, and clearing records with sender, recipient, and amount.',
    },
    requiredHeaders: 'Required Columns',
    recordsLabel: 'Records',
    selectCsv: 'Select CSV File to Upload',
    readingFile: 'Reading file...',
    feedbackSuccess: 'Operation Successful',
    feedbackError: 'File Reading Error',
    fileProcessed: 'File Processed',
    recordsCommitted: 'records verified and saved.',
    validLabel: 'Valid',
    rejectedLabel: 'Skipped',
    diagnosticsTitle: 'Data Quality Warnings & Auto-Fixes',
    scenariosTitle: 'Built-in Suspicious Pattern Scenarios',
    scenariosDescription: 'Fintel includes built-in demonstration data covering 7 standard types of suspicious activity (Rapid Pass-Through, Large Transfers, Structuring, Money Mule Networks, Rapid Dispersion, High-Frequency Bursts, and Circular Movement). Importing new data automatically updates the account connections map and recalculates risk levels.',
  },

  // Case Status Labels & Descriptions
  caseStatus: {
    new: 'Needs Initial Triage',
    underInvestigation: 'Investigation in Progress',
    pendingReview: 'Awaiting Your Review',
    reportDrafted: 'Awaiting Your Review',
    approved: 'Approved for Regulatory Filing',
    rejected: 'Closed — False Positive',
    closed: 'Resolved & Archived',
  },

  // Risk Level Labels
  riskLevels: {
    critical: 'Critical Risk',
    high: 'High Risk',
    medium: 'Medium Risk',
    low: 'Low Risk',
  },

  // Plain-Language Explanations for Common Terms
  terms: {
    aml: {
      term: 'AML',
      name: 'Anti-Money Laundering',
      plain: 'Rules and surveillance systems designed to prevent disguising illicit funds as legitimate money.',
    },
    cft: {
      term: 'CFT',
      name: 'Counter-Terror Financing',
      plain: 'Regulations and forensic tracking to detect and stop funding for unlawful groups.',
    },
    sar: {
      term: 'SAR',
      name: 'Suspicious Activity Report',
      plain: 'Official report submitted to authorities (like FIU-IND) when transactions look suspicious.',
    },
    fiuInd: {
      term: 'FIU-IND',
      name: 'Financial Intelligence Unit - India',
      plain: 'The central government agency that receives and analyzes suspicious financial activity reports.',
    },
    kyc: {
      term: 'KYC',
      name: 'Know Your Customer',
      plain: 'Identity checks confirming who the customer is and where their money comes from.',
    },
    pep: {
      term: 'PEP',
      name: 'Politically Exposed Person',
      plain: 'An individual with prominent public roles who requires closer regulatory scrutiny.',
    },
    ubo: {
      term: 'UBO',
      name: 'Ultimate Beneficial Owner',
      plain: 'The real person who ultimately owns or controls an account or company.',
    },
    structuring: {
      term: 'Structuring',
      name: 'Structuring (Smurfing)',
      plain: 'Breaking transfers into smaller amounts intentionally placed just under reporting limits ($10,000 / ₹10 Lakhs).',
    },
    layering: {
      term: 'Layering',
      name: 'Layering',
      plain: 'Moving money through multiple accounts and companies to hide where it originally came from.',
    },
    roundTripping: {
      term: 'Round-Tripping',
      name: 'Round-Tripping',
      plain: 'Sending money in circles through intermediary accounts and returning it disguised as legitimate business revenue.',
    },
    auditTrail: {
      term: 'Activity History',
      name: 'Audit Trail',
      plain: 'A permanent, unchangeable record of every action taken in the system by users and automated tools.',
    },
  },
} as const;

export default LABELS;
